FROM ghcr.io/home-assistant/home-assistant:stable

WORKDIR /config

#RUN mkdir -pv custom_components
#RUN touch custom_components/__init__.py
#
#COPY --chmod=777 custom_components/ktw_its custom_components/ktw_its
